read me
polinapechenkova/html_css pull request #1
Opened 2023-12-22 16:23 UTC by polinapechenkova

Привет! Проверьте, пожалуйста.

2023-12-24 19:41 UTC, Levitinn requested changes
нужно поправить отступы, и комментарии которые я указал

2023-12-24 19:41 UTC, Levitinn commented on 1-Blog/1-blog.html
> +            <li>Мой блог</li>
эти элементы должны быть ссылками

2023-12-24 19:41 UTC, Levitinn commented on 1-Blog/1-blog.html
> +       <section>12 мая 2024</section>
это не секции, а дивы

2023-12-24 19:41 UTC, Levitinn commented on 1-Blog/1-blog.html
снова проблема с отступами

2023-12-25 14:11 UTC, polinapechenkova commented
Привет! Все исправила.

2023-12-29 08:38 UTC, Levitinn requested changes

2023-12-29 08:38 UTC, Levitinn commented on 1-Blog/1-blog.html
> +        <input type="search" id="search" </nav> <header>
ошибка в верстке. обрати внимание, что закрывающий тег </nav> подсвечен красным. это потому что у тебя не закрывается тег инпут, который стоит перед ним

2023-12-29 08:38 UTC, Levitinn commented on 1-Blog/1-blog.html
> +        </header>
тег хедер расположен не верно. в данном случае, чаще всего, тег хедер - это шапка сайта. в твоем случае, nav должен лежать внутри хедера

2023-12-29 08:38 UTC, Levitinn commented on 1-Blog/1-blog.html
> +            <section>
это не секция, а обычный див, как и следующий тег (разработчик)

2023-12-29 08:38 UTC, Levitinn commented on 1-Blog/2-Form/2-form.html
а здесь все хорошо)

2024-01-02 10:32 UTC, polinapechenkova commented on 1-Blog/1-blog.html
> +            <section>
Привет! Исправила 1-Blog. 
Подскажи, пожалуйста, а pull request по js мне нужно самостоятельно будет слить с основной веткой (там, кажется, крайние исправления были приняты)?

2024-01-02 12:33 UTC, Levitinn approved these changes

2024-01-02 16:11 UTC, merged