2-css
polinapechenkova/html_css pull request #2
Opened 2024-01-04 00:36 UTC by polinapechenkova

Привет!
В Figma не получилось определить margin отступы между параграфами(

2024-01-05 15:42 UTC, Levitinn requested changes
как и говорил ранее, я не проверяю ДЗ если не соблюдены отступы и табуляция.
а так же, теги img всегда должны быть обернуты в отдельный div

2024-01-05 23:34 UTC, polinapechenkova commented
Привет! Добавила отступы и теги div для img. 
Надеюсь, сейчас форматирование правильное.

2024-01-08 19:46 UTC, Levitinn requested changes
А так же, графику для каждой страницы стоит класть в отдельную папку img.  ведь если, к примеру, на странице 100 картинок, представляешь как сложно будет найти нужные файлы, если они все лежат в одной папке?

2024-01-08 19:46 UTC, Levitinn commented on 1-Blog/girl.png
графику мы используем только тогда, когда этого требует макет, а все что можно сделать версткой, мы верстаем. твоя картинка включает в себя текст. верни обратно прошлую картинку и сделай текст в html=)

2024-01-09 14:54 UTC, polinapechenkova commented on 1-Blog/girl.png
Привет! Все исправила.

2024-01-09 17:47 UTC, Levitinn requested changes

2024-01-09 17:47 UTC, Levitinn commented on 1-Blog/1-blog.html
> +                    <div><img src="./img/brand.png" class="symbol" alt="значок бренда"></div><a href="#" class="first">Мой
Это же не картинка. в прошлом ревью я сказал о том, что все что можно сделать версткой, нужно делать версткой

2024-01-09 17:47 UTC, Levitinn commented on 1-Blog/1-blog.html
> +            <label for="search"></label>
label img и input лучше положить в один див, ведь это все относится к одному элементу

2024-01-09 19:09 UTC, polinapechenkova commented on 1-Blog/1-blog.html
> +            <label for="search"></label>
Привет! Учла комментарии.

2024-01-09 19:13 UTC, Levitinn requested changes

2024-01-09 19:13 UTC, Levitinn commented on 1-Blog/1-blog.html
> +                <li><a href="#" class="brand">B</a></li>
куда по твоему должна вести ссылка "В"? 
- правильно, никуда, потому что ссылкой является одна фраза "В Мой блог" это одна ссылка, не две. внутри этой ссылки один див "В" и второй див "Мой блог"

2024-01-11 18:06 UTC, Levitinn requested changes

2024-01-11 18:06 UTC, Levitinn commented on 1-Blog/1-blog.html
> +        <div class="developer">Разработчик</div>
girl, name, developer должны быть в одном общем диве

2024-01-11 18:06 UTC, Levitinn commented on 1-Blog/1-blog.html
> +        <p class="other">Универсального ответа на вопрос, как тот или иной цвет влияет на разных людей, нет.
other и last имеют одинаковые стили, потому и класс должен быть один. отступа у последнего "р" быть не должно, это отступ футера

2024-01-12 01:35 UTC, polinapechenkova commented on 1-Blog/1-blog.html
> +        <p class="other">Универсального ответа на вопрос, как тот или иной цвет влияет на разных людей, нет.
Исправила)

2024-01-12 01:36 UTC, polinapechenkova commented on 1-Blog/1-blog.html
> +        <div class="developer">Разработчик</div>
Если правильно понимаю, общий div должен объединять внутри себя три вложенных div.

2024-01-12 18:01 UTC, Levitinn requested changes

2024-01-13 17:32 UTC, merged