Код ревью 3.
polinapechenkova/html_css pull request #6
Opened 2024-02-07 04:26 UTC by polinapechenkova

Привет! К сожалению, не получилось правильно применить flex-раскладку к некоторым элементам, в частности к input (в 1-Blog), name и surname (в 2-Form), поэтому пришлось корректировать вручную :(

Можно, пожалуйста, узнать, как возможно картинку стрелки внутри button (в 2-Form) расположить справа согласно макету?

2024-02-07 19:19 UTC, Levitinn requested changes

2024-02-07 19:19 UTC, Levitinn commented on 1-Blog/1-blog.html
> +                    <input type="search" id="search" value='Поиск' />
неправильное позиционирование. если хочешь дать элементу отступ больше 40 пх, стоит подумать еще раз, это плохой знак. позиционируй через флекс

2024-02-07 19:19 UTC, Levitinn commented on 1-Blog/1-blog.html
>      <div class="hero">FRONTEND 12 мая 2024</div>
заканчивается хедер, начинается новая секция, а у тебя ее нет)

2024-02-07 19:19 UTC, Levitinn commented on 1-Blog/1-blog.html
>                  <div class="developer">Разработчик</div>
отступа снизу быть не должно у этого элемента. у всего блока должен

2024-02-11 08:19 UTC, polinapechenkova commented on 1-Blog/1-blog.html
>                  <div class="developer">Разработчик</div>
привет! постаралась учесть замечания.

2024-02-11 12:29 UTC, Levitinn requested changes

2024-02-11 12:29 UTC, Levitinn commented on 1-Blog/1-blog.css
> +        width: 1440px;
это не правильно. зачем задавать ширину к боди?

2024-02-11 12:29 UTC, Levitinn commented on 1-Blog/1-blog.html
> +    <section>
этот текст и блок про разработчика относятся к одной секции, а ты их разнесла по разным)

2024-02-11 12:29 UTC, Levitinn commented on 1-Blog/1-blog.html
> +                    <input type="search" id="search" value='Поиск' />
с инпутмо проблемка. смотри как он выглядит если взять его в фокус 
![Uploading image.png…]()

2024-02-11 12:29 UTC, Levitinn commented on 1-Blog/1-blog.html
>              <div class="girl">
у блока про разработчика сейчас родитель это див container2, что не совсем корректно. должен быть свой родитель с классом, например person

2024-02-11 12:29 UTC, Levitinn commented on 1-Blog/1-blog.css
> +        padding-right: 272px;
так делать нельзя. я писал тебе ранее про отступы. для выравнивания элементов стоит использовать другие свойства, например флекс

2024-02-11 12:29 UTC, Levitinn commented on 2-Form/2-form.html
>          <h1>Регистрация</h1>
что то тут не так. у этого заголовка и паддинги и марджины. а это должен быть паддинг самого блока формы

2024-02-11 12:29 UTC, Levitinn commented on 2-Form/2-form.html
> +            <div class="item item1">Моя компания:</div>
кажется это тоже должен быть инпут. нет?

2024-02-11 12:29 UTC, Levitinn commented on 2-Form/2-form.html
> +            <div class="item item1">Моя компания:</div>
а еще убери лишние стили у этого элемента. топ/лефт явно ни к месту

2024-02-11 12:29 UTC, Levitinn commented on 2-Form/2-form.html
> +                <div class="item item6">
у этого элемента не должно быть отступов

2024-02-11 12:29 UTC, Levitinn commented on 2-Form/2-form.html
>      <main>
ты задала строгие ширину и высоту для этого блока. так быть не должно, размеры сами сложатся исходя из контента формы

2024-02-13 07:51 UTC, polinapechenkova commented on 2-Form/2-form.html
>      <main>
привет! 

в 2-form, если не задать строгие размеры (как для main, так и для item-ов), все разъезжается, как можно этого избежать? :(

2024-02-13 14:08 UTC, Levitinn commented on 2-Form/2-form.html
>      <main>
можно задать max-width, и width: 100%
высота сложится из контента сама (но должна совпадать с макетом)
выровнять сам белый блок через флекс

2024-02-13 14:12 UTC, Levitinn commented on 2-Form/2-form.html
>          <h1>Регистрация</h1>
остался лишний марджин

2024-02-13 14:12 UTC, Levitinn commented on 2-Form/2-form.html
>          <h1>Регистрация</h1>
остался лишний марджин

2024-02-13 14:12 UTC, Levitinn commented on 2-Form/2-form.html
>          <h1>Регистрация</h1>
остался лишний марджин

2024-02-13 14:12 UTC, Levitinn commented on 2-Form/2-form.html
>          <h1>Регистрация</h1>
остался лишний марджин

2024-02-15 19:26 UTC, Levitinn approved these changes

2024-02-16 07:48 UTC, merged